version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_miprestamo
    restart: always
    environment:
      POSTGRES_USER: miprestamo_user
      POSTGRES_PASSWORD: miprestamo_password
      POSTGRES_DB: miprestamo_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
